config/routes.rb
Rails.application.routes.draw do
  get 'data/indicator'
  get 'data/dashboard'
  get 'data/questions'
  get 'data/lolcat'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "data#questions"
  get 'about' => 'pages#show', page: 'about'
  get 'contact' => 'pages#show', page: 'contact'
  post 'contact' => 'pages#contact'
  # get "/:page" => "pages#show"
  get "/fact/:fact_id" => "data#fact"

end

app/controllers/data_controller.rb
class DataController < ApplicationController
  layout "layer2", only: [:questions, :dashboard]

  def indicator
    @indicator = Indicator.find(params[:indicator_id])
    @country_ids = params[:country_ids]
    @years = params[:years]
    respond_to do |format|
      format.json { render json: @indicator.data(@country_ids, @years), status: :ok }
    end

  end

  def dashboard
    id = data_params[:indicator_id] unless data_params.nil?
    @indicator = Indicator.find(id || Indicator.first.id)
    country_ids = data_params[:country_ids].reject!(&:empty?) unless data_params.nil? || data_params[:country_ids].nil?
    @country_ids = country_ids || []
    years = data_params[:years].reject!(&:empty?) unless data_params.nil? || data_params[:years].nil?
    @years = years || []
    @max = @indicator.data(@country_ids, @years).each.map { |country| country['data'].values.compact.max }.max unless data_params.nil?
    @min = @indicator.data(@country_ids, @years).each.map { |country| country['data'].values.compact.min }.min unless data_params.nil?
    @minmax = [@min, @max]
  end

  def questions

    country_id = question_params[:country_id]unless question_params.nil?
    @country_id = country_id || Country.first.id
    @facts = Fact.where(factable_type: 'Question', country_id: @country_id)
    @questions = Question.where facts: @facts
    @question = Question.all.first
    @question_categories = QuestionCategory.all

  end

  def fact
    # layout "layer2"

    fact_id = params[:fact_id]
    @fact = Fact.find fact_id
    render layout: "empty"
  end

  private
    def data_params
      params.require(:indicator).permit(:indicator_id, country_ids: [], years: []) unless params[:indicator].nil?
    end

    def question_params
      params.permit(:question_id, :country_id)
    end
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/_data_table.html.erb
       <br> <br><br>
       <div class="table-responsive">
         <!--Table-->
        <table class="table small">
          <thead>
           <tr>
             <th scope="col">País</th>
             <% @years.each do |year| %>
               <th scope="col"><%= year %></th>
             <% end %>
           </tr>
         </thead>
         <tbody>
           <% @indicator.data(@country_ids, @years).each do |data_by_country| %>
             <tr>
               <% data_by_country["data"].each do |d| %>
                 <td> <%= d[1] %> </td>
               <% end %>
             </tr>
           <% end %>
         </tbody>
       </table> --> %>

       </div>

app/views/data/dashboard.html.erb
<section class="fullscreen-sections-wrapper">
   <div class="section-block fullscreen-section">
      <!-- Fullscreen Slider -->
      <div class="background-slider-wrapper">
         <div class="tm-slider-container fullscreen tms-fullscreen tms-caption-no-scaling show-on-hover" data-featured-slider="" data-fs-use-height="parent" data-auto-advance="" data-auto-advance-interval="4000" data-pause-on-hover="false" data-progress-bar="false" data-nav-arrows="false" data-nav-pagination="false" data-speed="2800" data-animation="fade" data-scale-under="1" style="top: 0px; left: 0px; width: 1035px; height: 698px;">
            <ul class="tms-slides">
               <li class="tms-slide active tms-forcefit" data-image="" data-force-fit="" id="tms-slide-1" style="transition: -webkit-transform 1000ms ease 0ms, opacity; opacity: 1; transform: translate3d(0px, 0px, 0px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) scale3d(1, 1, 1); transform-origin: 50% 50% 0px; visibility: visible;">
                  <img data-src="<%= asset_path 'datos-bg.png' %>" data-retina="" src="<%= asset_path 'datos-bg.png' %>" alt="" style="opacity: 1; width: 1091px; height: 698px; top: 0px; left: -28px;">
               </li>
            </ul>
         </div>
      </div>
      <!-- Fullscreen Slider End -->
      <!-- Fullscreen Inner -->
      <div class="fullscreen-inner">
        <div class="row tmh-perspective">
           <div class="column width-10 pt-60 offset-1 center horizon" data-animate-in="preset:slideInUpShort;duration:1000ms;" data-threshold="1" style="backface-visibility: hidden; transition: -webkit-transform 1000ms cubic-bezier(0.11, 0.69, 0.66, 1.01) 0s, opacity; transform: translate3d(0px, 0px, 0px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) scale3d(1, 1, 1); opacity: 1; visibility: visible; transform-origin: 50% 50% 0px;">
              <p class="text-medium lspacing-small mb-10 color-black title01">Para enfrentar la crisis </p>
              <div class="clear"></div>
              <p class="title-large no-padding-on-mobile lspacing-medium mb-10 weight-bold color-black">quienes tienen más</p>
              <p class="text-medium lspacing-small mb-10 color-black title01">deben pagar lo que corresponde</p>
              <div class="row">
                 <div class="column width-12 pt-30 pb-30 current">
                    <p class="color-black text-small">
                       Revisa aquí cómo impacta la evasión de impuestos en las vidas de los habitantes de América Latina
                    </p>
                    <a href="#datosparaactuar" class="icon-circled icon-down-open-mini medium scroll-link border-black bkg-hover-theme color-black color-hover-white no-margins" data-offset="-60"></a>
                 </div>
              </div>
           </div>
        </div>
      </div>
    </section>
    <!-- Datos Section -->
    <section id="datosparaactuar">
         <div class="row tmh-perspective">
            <div class="column width-10 pt-60 offset-1 center horizon" data-animate-in="preset:slideInUpShort;duration:1000ms;" data-threshold="1" style="backface-visibility: hidden; transition: -webkit-transform 1000ms cubic-bezier(0.11, 0.69, 0.66, 1.01) 0s, opacity; transform: translate3d(0px, 0px, 0px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) scale3d(1, 1, 1); opacity: 1; visibility: visible; transform-origin: 50% 50% 0px;">
              <h1 class="inline no-margin-bottom">Datos en detalle</h1>
                <%= form_with model: @indicator, method: :get, local: true, url: data_dashboard_path, class: "" do |f| %>
                  <div class="row">
                    <div class="column width-2 pt-30  current"> </div>
                    <div class="column width-8 pt-30  current">
                      <h2> 1. Elige el indicador </h2>
                      <div class="form-select form-element small">
                        <%= f.collection_select(:indicator_id, Indicator.order('name ASC'), :id, :name, {:prompt => 'Selecciona el indicador', :selected => @indicator.id}, {multiple: false, class: 'form-aux'}) %>
                      </div>
                    </div>
                    <div class="column width-2 pt-30  current"> </div>
                  </div>

                  <!-- <div class="row">
                    <div class="column width-2 pb-30 current"></div>
                    <div class="column width-4 pb-30 current">
                      <h2> 2. Elige los países </h2>
                      <div class="form-select form-element small">
                        <%= f.collection_select(:country_ids, Country.all, :id, :name, {:prompt => 'Selecciona los países',:selected => @country_ids}, { multiple: true, class: 'form-aux' }) %>
                      </div>
                    </div>

                    <div class="column width-4 pb-30 current">
                      <h2> 2. Elige los años </h2>
                      <div class="form-select form-element small">
                        <%= f.select(:years, (2000..2018).collect {|p| [ p, p ] }, {:prompt => 'Selecciona años', :selected => @years }, { multiple: true, class: 'form-aux' }) %>
                      </div>
                    </div>

                    <div class="column width-2 pb-30 current"></div>

                  </div> -->

                  <%= f.submit "Revisar indicador" %>

                <% end %>

               </div>
            </div>
         </div>
      </div>
</section>

<% if @indicator.data(@country_ids, @years).empty? %>


<div class="content clearfix">
  <div class="section-block pb-0">
   <div class="row">
     <div class="column width-10 offset-1 center">

       <p class="lead weight-bold mb-70 pt-50"> No hay datos para esta búsqueda </p>

     </div>
   </div>
 </div>
</div>

<% else %>
<!-- Content -->
<div class="content clearfix">
  <div class="section-block pb-0">
   <div class="row">
     <div class="column width-10 offset-1 center">

       <p class="lead weight-bold mb-70 pt-50"> <%= @indicator.name %> </p>

       <p> <%= @indicator.description %> </p>

       <p><%= image_tag @indicator.icon if @indicator.icon.attached?%></p>

       <%= line_chart @indicator.data(@country_ids, @years).each.map { |country|
           {name: country['label'], data: country['data']}
         },
          min: @minmax.first,
          max: @minmax.last,
          code: false,
          download: {background: "#ffffff", filename: "dataigualdad-chart"},
          legend: "bottom",
          xtitle: "Año", ytitle: @indicator.name.truncate(45), height: "450px"  %>

     </div>
   </div>
   <div class="row">
     <div class="column width-10 offset-1 center">
        <p class="lead weight-bold mb-70 pt-30">Notas:</p>
        <ol>
          <% @indicator.notes.each do |note| %>
          <li><%= note.text %></li>
          <% end %>
        </ol>
      </div>
   </div>
 </div>
</div>
<% end %>

app/views/data/dashboard.html.haml
%h1 Data#dashboard
%p Find me in app/views/data/dashboard.html.haml


= form_with model: @indicator, remote: true, method: :get, url: data_indicator_path, class: "" do |f|
  = f.text_field :title
  = f.collection_select(:indicator_id, Indicator.all, :id, :name, {:prompt => 'Please select the indicator'})
  = f.collection_select(:country_ids, Country.all, :id, :name, {:prompt => 'Please select the countries'}, { multiple: true })
  = f.select(:years, (1990..2018).collect {|p| [ p, p ] }, { include_blank: true }, { multiple: true })
  = f.submit "Create"

=  @indicator.data.map { |row|
  %p {name: row.key, data: row.values}
  }

app/views/data/fact.html.erb
<% content_for :og_details do %>
  <meta property="og:title"           content="DataIgualdad" />
  <meta property="og:url"             content="<%= root_url %>fact/<%=@fact.id%>" />
  <meta property="og:description"     content="<%= @fact.question_text %>" />
  <meta property="og:type"            content="article" />
  <meta property="fb:app_id"          content="2410108469250484" />
  <meta name="twitter:card"           content="summary_large_image" />
  <meta name="twitter:site"           content="@ciudadaniai" />
  <meta name="twitter:creator"        content="@ciudadaniai" />
  <% if @fact.slide.attached? %>
    <meta property="og:image"         content='<%=root_url%><%= url_for(@fact.slide.attachment) %>'/>
    <meta property="og:image:width"   content="2500" />
    <meta property="og:image:height"  content="1600" />
    <meta name="twitter:image"        content="<%=root_url%><%= url_for(@fact.slide.attachment) %>">
  <% end %>
<% end %>

<section class="fullscreen-sections-wrapper">
  <div class="column width-12 center fact-section">
    <a id="tml-exit" class="tml-nav" onclick="history.back()"></a>
           <div class="image">
              <%= image_tag @fact.slide if @fact.slide.attached? %>
              <h3 class="center pt-10 pb-0"> Comparte este dato en Redes Sociales </h3>
              <div class="social-share-button" data-title="{:url=><%= root_url%>;, :image=><%= url_for(@fact.slide.attachment) if @fact.slide.attached?%>;}" data-img="" data-url="" data-desc="" data-via="">

                <a rel="nofollow " data-site="twitter" class="ssb-icon ssb-twitter" title="Share to Twitter" onclick="popUp=window.open('https://twitter.com/intent/tweet?text=<%=u @fact.factable.question_category.message %>&amp;url=<%= root_url %>fact/<%=@fact.id%>&amp;related=ciudadania_i', 'popupwindow', 'scrollbars=yes,width=800,height=400');popUp.focus();return false;" href="javascript: void(0)"></a>

                <a rel="nofollow " data-site="facebook" class="ssb-icon ssb-facebook"  title="Share to Facebook" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=<%= root_url %>fact/<%=@fact.id%>', 'sharer', 'width=626,height=436');" href="javascript: void(0)" >
                </a>

                <a rel="nofollow " data-site="email" class="ssb-icon ssb-email" onclick="return SocialShareButton.share(this);" title="Share to Email" href="#"></a>

                <a rel="nofollow " data-site="linkedin" class="ssb-icon ssb-linkedin" onclick="return SocialShareButton.share(this);" title="Share to Linkedin" href="#"></a>

                <!-- <a rel="nofollow " data-site="reddit" class="ssb-icon ssb-reddit" onclick="return SocialShareButton.share(this);" title="Share to Reddit" href="#"></a> -->

                <a rel="nofollow " data-site="telegram" class="ssb-icon ssb-telegram" onclick="return SocialShareButton.share(this);" title="Share to Telegram" href="#"></a>

                <a rel="nofollow " data-site="whatsapp_app" class="ssb-icon ssb-whatsapp_app" href="whatsapp://send?text=<%= root_url %>fact/<%=@fact.id%>"></a>

              </div>

           </div>
    </div>
</section>

app/views/data/indicator.html.haml
%h1 Data#indicator
%p Find me in app/views/data/indicator.html.haml

app/views/data/questions.html.erb
<section class="fullscreen-sections-wrapper">
   <div class="section-block fullscreen-section">
      <!-- Fullscreen Slider -->
      <div class="background-slider-wrapper">
         <div class="tm-slider-container fullscreen tms-fullscreen tms-caption-no-scaling show-on-hover" data-featured-slider="" data-fs-use-height="parent" data-auto-advance="" data-auto-advance-interval="4000" data-pause-on-hover="false" data-progress-bar="false" data-nav-arrows="false" data-nav-pagination="false" data-speed="2800" data-animation="fade" data-scale-under="1" style="top: 0px; left: 0px; width: 1035px; height: 698px;">
            <ul class="tms-slides">
               <li class="tms-slide active tms-forcefit" data-image="" data-force-fit="" id="tms-slide-1" style="transition: -webkit-transform 1000ms ease 0ms, opacity; opacity: 1; transform: translate3d(0px, 0px, 0px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) scale3d(1, 1, 1); transform-origin: 50% 50% 0px; visibility: visible;">
                  <img data-src="<%= asset_path 'desigualdad-bg.png' %>" data-retina="" src="<%= asset_path 'desigualdad-bg.png' %>" alt="" style="opacity: 1; width: 1091px; height: 698px; top: 0px; left: -28px;">
               </li>
            </ul>
         </div>
      </div>
      <!-- Fullscreen Slider End -->
      <!-- Fullscreen Inner -->
      <div class="fullscreen-inner">
         <div class="row tmh-perspective">
            <div class="column width-10 pt-60 offset-1 center horizon" data-animate-in="preset:slideInUpShort;duration:1000ms;" data-threshold="1" style="backface-visibility: hidden; transition: -webkit-transform 1000ms cubic-bezier(0.11, 0.69, 0.66, 1.01) 0s, opacity; transform: translate3d(0px, 0px, 0px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) scale3d(1, 1, 1); opacity: 1; visibility: visible; transform-origin: 50% 50% 0px;">
               <p class="text-medium lspacing-small mb-10 color-black title01">Para enfrentar la crisis </p>
               <div class="clear"></div>
               <p class="title-large no-padding-on-mobile lspacing-medium mb-10 weight-bold color-black">quienes tienen más</p>
               <p class="text-medium lspacing-small mb-10 color-black title01">deben pagar lo que corresponde</p>
               <div class="row">
                  <div class="column width-12 pt-30 pb-30 current">
                     <p class="color-black text-small">
                        Revisa aquí cómo impacta la evasión de impuestos en las vidas de los habitantes de América Latina
                     </p>
                     <a href="#datosparaactuar" class="icon-circled icon-down-open-mini medium scroll-link border-black bkg-hover-theme color-black color-hover-white no-margins" data-offset="-60"></a>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- Fullscreen Inner -->
   </div>
</section>
<!-- Datos Section -->
<section id="datosparaactuar">
  <div class="row no-padding">
    <div class="column width-12 pt-30 pb-30 current">
    <p class="color-black text-small">
    Saber cómo se distribuyen los recursos públicos nos permite tomar posición para reducir la desigualdad. Revisa aquí una serie de datos por país sobre cómo los montos que deberían destinarse al pago de impuestos podrían ayudar a enfrentar la crisis. 
    </p>
    </div>
  </div>
   <div class="section-block grid-filter-menu pt-110 right left-on-mobile">
      <div class="row no-padding">
         <div class="column width-6">
          <p>Selecciona un país y revisa sus datos</p>
         </div>
      </div>
      <div class="row">
         <div class="column width-6 offset-3">
            <div class="form-select form-element large">
               <%= form_with method: :get, local: true, url: data_questions_path, class: "" do |f| %>
               <br>
               <%= f.collection_select(:country_id, Country.all, :id, :name, {:prompt => 'Elige un país',:selected => @country_id}, { multiple: false, class: 'form-aux', onchange: 'this.form.submit();' }) %>
               <br>
               <% f.submit "Show" %>
               <% end %>
            </div>
         </div>
      </div>
      <div class="row">   
         <div class="column width-12 left">
            <ul>
               <li><a class="active" href="#" data-filter="*">Todos</a></li>
               <% @question_categories.reverse_each do |cat|%>
               <li><a href="#" data-filter=".<%= cat.short_name %>"><%= cat.name %></a></li>
               <% end %>
            </ul>
         </div>
      </div>
   </div>
   <div class="section-block grid-container fade-in-progressively small-margins no-padding-top" data-layout-mode="masonry" data-grid-ratio="1.5" data-animate-filter-duration="700" data-animate-resize data-animate-resize-duration="0">
      <div class="row">
         <div class="column width-12">
            <div class="row grid content-grid-3">
               <% @facts.each do |fact| %>
               <!-- image template  -->
               <div class="grid-item grid-sizer <%= fact.factable.question_category.short_name.to_s if fact.factable  %>">

                  <div class="image-concept-text">
                     <p><%= fact.factable.concept if fact.factable %></p>
                  </div>
                  <div class="title-container-inner color-black">
                     <h2 class="inline">Respuesta</h2>
                  </div>

                  <div class="question_text thumbnail img-scale-in"  data-hover-easing="easeInOut" data-hover-speed="500" data-hover-bkg-color="#000000" data-hover-bkg-opacity="0.8">
                     <!--<a class="overlay-link lightbox-link" data-group="gallery-1">-->
                     <div>
                        <!-- <a class="overlay-link lightbox-link" data-group="gallery-1" data-image-url="<%= url_for(fact.slide) if fact.slide.attached? %>" href="<%= fact.path if fact.slide.attached? %>">
                           <%= image_tag fact.slide if fact.slide.attached? %>
                           -->
                        <a class="overlay-link not-lightbox-link" data-group="gallery-1" data-image-url="<%= url_for(fact.slide) if fact.slide.attached? %>" href="<%= fact.path %>">
                        <%= image_tag fact.slide if fact.slide.attached? %>
                        <span class="overlay-info v-align-bottom left">
                        <span>
                        <span>
                        <span class="project-description"><span class="icon-eye left"> </span>
                        Ver imagen
                        </span>
                        </span>
                        </span>
                        </span>
                     </div>
                  </div>

                    <br>

                    <div class="social-share-button" data-title="{:url=><%= root_url%>;, :image=><%= url_for(fact.slide.attachment) if fact.slide.attached?%>;}" data-img="" data-url="" data-desc="" data-via="">

                      <a rel="nofollow " data-site="twitter" class="ssb-icon ssb-twitter" title="Share to Twitter" onclick="popUp=window.open('https://twitter.com/intent/tweet?text=<%=u fact.factable.question_category.message%>&amp;url=<%= root_url %>fact/<%=fact.id%>&amp;related=ciudadania_i', 'popupwindow', 'scrollbars=yes,width=800,height=400');popUp.focus();return false;" href="javascript: void(0)"></a>

                      <a rel="nofollow " data-site="facebook" class="ssb-icon ssb-facebook"  title="Share to Facebook" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=<%= root_url %>fact/<%=fact.id%>', 'sharer', 'width=626,height=436');" href="javascript: void(0)" >
                      </a>

                      <a rel="nofollow " data-site="email" class="ssb-icon ssb-email" onclick="return SocialShareButton.share(this);" title="Share to Email" href="#"></a>

                      <a rel="nofollow " data-site="linkedin" class="ssb-icon ssb-linkedin" onclick="return SocialShareButton.share(this);" title="Share to Linkedin" href="#"></a>

                      <!-- <a rel="nofollow " data-site="reddit" class="ssb-icon ssb-reddit" onclick="return SocialShareButton.share(this);" title="Share to Reddit" href="#"></a> -->

                      <a rel="nofollow " data-site="telegram" class="ssb-icon ssb-telegram" onclick="return SocialShareButton.share(this);" title="Share to Telegram" href="#"></a>

                      <a rel="nofollow " data-site="whatsapp_app" class="ssb-icon ssb-whatsapp_app" href="whatsapp://send?text=<%= root_url %>fact/<%=fact.id%>"></a>

                    </div>

               </div>
               <!-- end image template  -->
               <% end %>
            </div>
         </div>
      </div>
   </div>
</section>
<!-- Datos Section -->