config/routes.rb
Rails.application.routes.draw do
  get 'data/indicator'
  get 'data/dashboard'
  get 'data/questions'
  get 'data/lolcat'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "data#questions"
  get 'about' => 'pages#show', page: 'about'
  get 'contact' => 'pages#show', page: 'contact'
  post 'contact' => 'pages#contact'
  # get "/:page" => "pages#show"
  get "/fact/:fact_id" => "data#fact"

end

app/views/layouts/_descarga.html.erb
<!-- Descarga Section -->
<section>
   <div class="section-block replicable-content pt-60 pb-30 call-to-action-2 call-to-action-2-1 bkg-grey-ultralight">
      <div class="row">
         <div class="column width-6 offset-1 right center-on-mobile color-black">
            <p class="weight-normal">Descarga acá todos los datos en formato Excel</p>
         </div>
         <div class="column width-4 left center-on-mobile">
            <a target="_blank" href="https://docs.google.com/spreadsheets/d/1x77lgo5Z2ksxfvAwcDLsRhSO4z8tC4Gc9c_sGHrqiX8" onclick="myFunction();"class="button bkg-theme border-hover-black color-white color-hover-black mb-mobile-30 medium">Descargar base de datos para actuar</a>
            <script>
              function myFunction() {
                // document.getElementById("demo").innerHTML = "Hello World";
                gtag('event', 'download', {
                  'document': '1',
                  'screen_name': 'descarga'
                });

              }
            </script>
         </div>
      </div>
   </div>
</section>
<!-- Descarga Section -->

app/views/layouts/_elaborado.html.erb
<!-- Elaborado por -->
<div class="section-block logos-1 pt-50 pb-50 bkg-white color-charcoal">
   <div class="row">
      <div class="column width-3 center-on-mobile">
         <h3 class="mb-mobile-3 pt-20">Con apoyo de:</h3>
      </div>
      <div class="column width-9">
         <div class="row content-grid-3">
            <div class="grid-item">
               <a href="https://www.oxfam.org/es">
               <!-- <img src="images/logo-oxfam.png" alt=""/> -->
               <%= image_tag 'logo-oxfam.png' %>
               </a>
            </div>
            <div class="grid-item">
               <a href="https://www.latindadd.org/">
               <!-- <img src="images/logo-latindadd.png" alt=""/> -->
               <a href="https://ciudadaniai.org">
                 <%= image_tag 'logo-ciudadaniai.png' %>
               </a>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- Elaborado por -->

app/views/layouts/_extra.html.erb
<!-- Elaborado por -->
<div class="section-block logos-1 pt-50 pb-50 bkg-white color-charcoal">
   <div class="row">
      <div class="column width-3 center-on-mobile">
         <h3 class="mb-mobile-3 pt-20"> Extra : </h3>
      </div>
      <div class="column width-9">
        <div>
          <%= yield %>
        </div>
      </div>
   </div>
</div>
<!-- Elaborado por -->

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="footer">
   <div class="footer-top">
      <div class="row flex">
         <div class="column width-6">
            <div class="widget">
               <h4 class="widget-title">Mapa de sitio</h4>
               <ul>
                  <li>
                     <%= link_to root_path do %>
                      Inicio
                     <% end %>
                  </li>
                  <li>
                    <%= link_to about_path do %>
                     Quiénes somos
                    <% end %>
                  </li>
                  <!-- <li>
                     <a href="open-data.html">OpenData</a>
                  </li> -->
                  <li>
                     <%= link_to data_questions_path do %>
                      Datos para actuar
                     <% end %>
                  </li>
                  <li>
                    <%= link_to contact_path do %>
                     Contacto
                    <% end %>
                  </li>
               </ul>
               <div class="divider hide show-on-mobile no-margin-top"></div>
            </div>
         </div>
         <div class="column width-5 offset-1">
            <div class="widget">
               <h4 class="widget-title">#DataIgualdad</h4>
               <p>DataIgualdad está en proceso de actualización, próximamente publicaremos la versión actualizada de todos los indicadores del sitio. ¿Quieres acceder a la base de datos original del proyecto?
               </p>
                <a class="button button-datos small
                bkg-datos bkg-hover-datos color-white color-hover-white no-margin-bottom" href="https://drive.google.com/file/d/1wUNZKyRz8dSM5imz8C5QG6EFqCcsiSDS/view"  onclick="myFunctionga(1);" target="_blank"></small>Descarga aquí la base de datos</span></a>
                <a class="button button-datos small
                bkg-datos bkg-hover-datos color-white color-hover-white no-margin-bottom" href="https://drive.google.com/file/d/1wUNZKyRz8dSM5imz8C5QG6EFqCcsiSDS/view"  onclick="myFunctionga(1);" target="_blank"></small>Descarga aquí la base de datos</span></a>
                <a class="button button-datos small
                bkg-datos bkg-hover-datos color-white color-hover-white no-margin-bottom" href="/DataIGUALDAD_metodología_1_0818.pdf"  onclick="myFunctionga(2);"target="_blank"></small>Metodología</span></a>
                <script>
                  function myFunctionga(doc) {
                    // alert(doc)
                    gtag('event', 'download', {
                      'document': doc,
                      'screen_name': doc
                    });
                  }
                </script>
            </div>
         </div>
      </div>
   </div>
</footer>
<!-- Footer -->

app/views/layouts/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Z5100ESELP"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Z5100ESELP');
</script>

app/views/layouts/_head.html.erb
<meta charset="UTF-8" />
<meta content="width=device-width,initial-scale=1.0,maximum-scale=1.0" name="viewport">
<meta name="twitter:widgets:theme" content="light">
<%= yield :og_details %>
<!-- <meta property="og:title" content="DataIgualdad" />
<meta property="og:type" content="DataIgualdad" />
<meta property="og:image" content="dataigualdad.org" /> -->
<title>DataIgualdad</title>
<link rel="shortcut icon" type="image/x-icon" href=<%= image_path "favicon.ico" %>>
<!-- Font -->
<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:100,100i,300,300i,400,400i,600,600i,700,700i&display=swap&subset=latin-ext" rel="stylesheet">
<!-- Css -->
<!-- <link rel="stylesheet" href="css/core.min.css" />
<link rel="stylesheet" href="css/skin-data.css" /> -->
<meta property="og:title"           content="DataIgualdad" />
<meta property="og:url"             content="<%= root_url %>" />
<meta property="og:description"     content="Los privilegios de unos pocos construyen la desigualdad de las mayorías. Infórmate sobre cómo se distribuyen los recursos de todas y todos en DataIgualdad." />
<meta property="og:type"            content="article" />
<meta property="fb:app_id"          content="2410108469250484" />
<meta name="twitter:card"           content="summary_large_image" />
<meta name="twitter:site"           content="@ciudadaniai" />
<meta name="twitter:creator"        content="@ciudadaniai" />
<meta property="og:image"         content='<%=root_url%><%= image_path "dataigualdad_image.png" %>'/>
<meta property="og:image:width"   content="1080" />
<meta property="og:image:height"  content="1080" />
<meta name="twitter:image"        content="<%=root_url%><%= image_path "dataigualdad_image.png" %>">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<!-- Header -->
<header class="header header-absolute header-fixed-on-mobile header-transparent" data-helper-in-threshold="300" data-helper-out-threshold="500" data-sticky-threshold="300" data-bkg-threshold="300" data-compact-threshold="300">
  <div class="header-inner">
     <div class="row nav-bar">
        <div class="column width-12 nav-bar-inner">
           <div class="logo">
              <div class="logo-inner">
                 <%= link_to root_path, {:class => "navbar-brand brand-logo"} do %>
                   <%= image_tag 'logo-dark.png' %>
                 <% end %>
                 <%= link_to root_path do %>
                   <%= image_tag 'logo.png' %>
                 <% end %>
              </div>
           </div>
           <nav class="navigation nav-block secondary-navigation nav-right">
              <ul>
                 <li>
                    <div class="v-align-middle">
                       <ul class="social-list list-horizontal">
                          <li><a href="#" class="nav-icon"><span class="icon-twitter small"></span></a></li>
                          <li><a href="#" class="nav-icon"><span class="icon-facebook small"></span></a></li>
                          <li><a href="#" class="nav-icon"><span class="icon-instagram small"></span></a></li>
                       </ul>
                    </div>
                 </li>
                 <li class="aux-navigation hide">
                    <!-- Aux Navigation -->
                    <a href="#" class="navigation-show side-nav-show nav-icon">
                    <span class="icon-menu"></span>
                    </a>
                 </li>
              </ul>
           </nav>
           <nav class="navigation nav-block primary-navigation sub-menu-indicator nav-right no-margin-right">
              <ul>
                 <li class="current">
                    <%= link_to data_questions_path do %>
                     Datos para actuar
                    <% end %>
                 </li>
                 <li>
                    <%= link_to about_path do %>
                     Quiénes somos
                    <% end %>
                 </li>
                 <li>
                   <%= link_to data_dashboard_path do %>
                    Base de datos
                   <% end %>
                 </li>
                 <li>
                    <%= link_to contact_path do %>
                     Contacto
                    <% end %>
                 </li>
              </ul>
           </nav>
        </div>
     </div>
  </div>
</header>
<!-- Header End -->

app/views/layouts/_questions.html.erb
<!-- Datos Section -->
<section id="datosparaactuar">
   <div class="section-block grid-filter-menu pt-110 right left-on-mobile">
      <div class="row no-padding">
        <div class="column width-4 left">
                 <div class="form-select form-element large">
                    <%= form_with method: :get, local: true, url: data_questions_path, class: "" do |f| %>
                      <br>
                      <%= f.collection_select(:country_id, Country.all, :id, :name, {:prompt => 'Elige un país',:selected => @country_id}, { multiple: false, class: 'form-aux', onchange: 'this.form.submit();' }) %>
                      <br>
                      <% f.submit "Show" %>
                    <% end %>
                 </div>
              </div>
         <div class="column width-8">
            <ul>
              <li><a class="active" href="#" data-filter="*">Todos</a></li>
              <% @question_categories.each do |cat|%>
               <li><a href="#" data-filter=".<%= cat.short_name %>"><%= cat.name %></a></li>
              <% end %>
            </ul>
         </div>
      </div>
   </div>
   <div class="section-block grid-container fade-in-progressively small-margins no-padding-top" data-layout-mode="masonry" data-grid-ratio="1.5" data-animate-filter-duration="700" data-set-dimensions data-animate-resize data-animate-resize-duration="0">
      <div class="row">
         <div class="column width-12">
            <div class="row grid content-grid-3">
              <% @facts.each do |fact| %>
              <!-- image template  -->
               <div class="grid-item grid-sizer <%= fact.factable.question_category.short_name %>">

                 <div class="question_text thumbnail img-scale-in"  data-hover-easing="easeInOut" data-hover-speed="500" data-hover-bkg-color="#000000" data-hover-bkg-opacity="0.8">

                    <!--<a class="overlay-link lightbox-link" data-group="gallery-1">-->
                     <div>

                    <%= image_tag fact.factable.background if fact.factable.background.attached? %>
                    <div class="image-question-text">
                       <p><%= fact.question_text %></p>
                    </div>

                    <div class="image-question-subtext">
                       <p><%= "La desigualdad atenta contra la democracia" %></p>
                    </div>

                    <div class="image-question-hashtag">
                       <p>#DataIgualdad #DatosParaActuar #<%= Country.find(@country_id).name %></p>
                    </div>
                     <span class="overlay-info v-align-bottom left">
                     <span>
                     <span>
                     <span class="text-line bkg-black mb-10"></span>

                     <span class="project-description"><span class="icon-share left"></span>
                       Compartir
                      </span>
                     <span class="text-line bkg-black mb-10"></span>
                       <%= social_share_button_tag(fact.question_text) %>

                     </span>
                     </span>
                     </span>
                     </div>
                     <!--</a>-->

                 </div>

               </div>
                 <!-- end image template  -->
                 <% end %>
            </div>
         </div>
      </div>
   </div>
</section>
<!-- Datos Section -->

app/views/layouts/_side_navigation.html.erb
<!-- Side Navigation Menu -->
<aside class="side-navigation-wrapper enter-right" data-no-scrollbar data-animation="push-in">
   <div class="side-navigation-scroll-pane">
      <div class="side-navigation-inner">
         <div class="side-navigation-header">
            <div class="navigation-hide side-nav-hide">
               <a href="#">
               <span class="icon-cancel medium"></span>
               </a>
            </div>
         </div>
         <nav class="side-navigation">
            <ul>
               <li>
                  <%= link_to root_path do %>
                    Inicio
                  <% end %>
               </li>
               <li>
                  <%= link_to about_path do %>
                    Quiénes somos
                  <% end %>
               </li>
               <li>
                  <%= link_to root_path do %>
                    Datos para actuar
                  <% end %>
               </li>
               <li>
                  <%= link_to contact_path do %>
                    Contacto
                  <% end %>
               </li>
            </ul>
         </nav>
         <div class="side-navigation-footer">
            <ul class="social-list list-horizontal">
               <li><a href="#"><span class="icon-twitter small"></span></a></li>
               <li><a href="#"><span class="icon-facebook small"></span></a></li>
               <li><a href="#"><span class="icon-instagram small"></span></a></li>
            </ul>
         </div>
      </div>
   </div>
</aside>
<!-- Side Navigation Menu End -->

app/views/layouts/_top_nav_bar.html.erb
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="navbar-brand-wrapper d-flex align-items-center">
        <%= link_to root_path, {:class => "navbar-brand brand-logo"} do %>
          <%= image_tag "logo.svg" %>
        <% end %>

        <%= link_to root_path, {:class => "navbar-brand brand-logo-mini"} do %>
          <%= image_tag "logo-mini.svg" %>
        <% end %>
        
    </div>

    <div class="navbar-menu-wrapper d-flex align-items-center flex-grow-1">
        <a class="nav-link" href="#" data-toggle="dropdown" aria-expanded="false">Inicio</a>
        <a class="nav-link" href="#" data-toggle="dropdown" aria-expanded="false">Quiénes somos</a>
        <a class="nav-link" href="#" data-toggle="dropdown" aria-expanded="false">FAQ</a>
        <a class="nav-link" href="#" data-toggle="dropdown" aria-expanded="false">Contacto</a>
        <ul class="navbar-nav navbar-nav-right ml-auto">
            <form class="search-form d-none d-md-block" action="#">
                <i class="icon-magnifier"></i>
                <input type="search" class="form-control" placeholder="Busca acá" title="Search here">
            </form>
            <li class="nav-item dropdown language-dropdown d-none d-sm-flex align-items-center">
                <a class="nav-link d-flex align-items-center dropdown-toggle" id="LanguageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                  <div class="d-inline-flex mr-3">
                      <i class="flag-icon flag-icon-es"></i>
                    </div>
                    <span class="profile-text font-weight-normal">Español</span>
                </a>
                <div class="dropdown-menu dropdown-menu-left navbar-dropdown py-2" aria-labelledby="LanguageDropdown">
                    <a class="dropdown-item">
                        <i class="flag-icon flag-icon-es"></i> Español </a>
                    <a class="dropdown-item">
                        <i class="flag-icon flag-icon-br"></i> Portugués </a>
                </div>
            </li>

        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="icon-menu"></span>
        </button>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">

<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dataigualdad</title>

    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="home-page">
    <%= render 'layouts/side_navigation' %>

    <div class=".container-scroller">
      <%= render 'layouts/top_nav_bar' %>
    </div>

    <div class="container-fluid page-body-wrapper">
      <div class="main-panel">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html lang="es">

<html>
  <head>

    <% if Rails.env.production? %>
      <%= render 'layouts/google_analytics' %>
    <% end %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dataigualdad</title>

    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :og_details %>
  </head>

  <body>

  <%= yield %>
  <!-- Go to www.addthis.com/dashboard to customize your tools -->
<!-- <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5dd9757bb1413ba2"></script> -->

  </body>
</html>

app/views/layouts/layer2.html.erb
<!DOCTYPE html>
<html lang="es">

<html>
  <head>
    <%= render 'layouts/head' %>
    <% if Rails.env.production? %>
      <%= render 'layouts/google_analytics' %>
    <% end %>
  </head>

  <body class="home-page">
    <%= render 'layouts/side_navigation' %>
    <div class="wrapper reveal-side-navigation">
       <div class="wrapper-inner">
         <%= render 'layouts/header' %>
          <!-- Content -->
          <div class="content clearfix">
             <!-- Hero home Section -->

             <!-- Hero home Section -->
             <%= yield %>

             <%= render 'layouts/descarga' %>
          </div>
          <!-- Content End -->
          <%= render 'layouts/elaborado' %>
          <%= render 'layouts/footer' %>
       </div>
    </div>


    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> -->
    <%# <%= javascript_pack_tag 'timber', 'data-turbolinks-track': 'reload' %>

    <script src="../js/jquery-1.12.4.min.js"></script>
    <!-- <script src=“https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js”></script> -->
    <script src="../js/timber.master.min.js"></script>
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <!-- <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5dd9757bb1413ba2"></script> -->

  </body>
</html>